name: 'EAS Notify'
description: 'Create a Slack message when EAS builds are ready'
inputs:
  easOutputFile:
    description: 'Path to a file containing output of the EAS build command'
    require: true
  slackWebhook:
    description: 'The webhook URL of your Slack app'
    require: true
runs:
  using: 'node12'
  main: 'dist/index.js'
